config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/pufowns', as: 'rails_admin'
  root to: 'mural#listar'
  get '/admin' => 'static#rickroll'
  get '/xelinhos' => 'static#rickroll'
  get '/pufowns' => 'static#rickroll'
  get '/:id' => 'mural#mostrar', as: 'mural'
  post '/:id' => 'mural#adicionar', as: 'enviar'
  get '/(*id)' => 'mural#listar'
end

app/models/mural.rb
class Mural < ActiveRecord::Base
  has_many :recados

  rails_admin do
    object_label_method :dono
  end
end

app/models/recado.rb
class Recado < ActiveRecord::Base
  belongs_to :mural

  rails_admin do
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mural_controller.rb
class MuralController < ApplicationController
  def mostrar
    @mural = Mural.find_by_id(params[:id])
    if not @mural.present?
      redirect_to('/404')
      return
    end
    @recados = @mural.recados
  end
  def listar
    @lista = Mural.all.order(dono: :asc)
  end
  def adicionar
    @mural = Mural.find_by_id(params[:id])
    if not @mural.present?
      redirect_to('/404')
      return
    end
    Recado.create(mensagem: params[:m].to_s, mural: @mural)
    @recados = @mural.recados
    render 'mostrar'
  end
  def listar_top
    @lista_crua = Mural.joins(:recados).order('count(recados.id) ASC').pluck('murals.id, murals.dono, count(recados.id)')
    @lista=@lista_crua.map{|i| {id: i[0], dono: i[1], recados: i[2] } }
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def rickroll
    redirect_to('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mural_helper.rb
module MuralHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amigosecreto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mural/listar.html.erb
<h1>Escolha um mural para deixar um recado!</h1>
<div class="caixa">
  <% @lista.each do |mural| %>
  <a href="<%= mural_path(mural.id) -%>">
    <div class="seletor">
      <h4><%= mural.dono -%></h4>
    </div>
  </a>
  <% end %>
</div>

app/views/mural/listar_top.html.erb
<h1>Escolha um mural para deixar um recado!</h1>
<div class="caixa">
  <% @lista.each do |mural| %>
  <a href="/<%= mural[:id] -%>">
    <div class="seletor">
      <h4><%= "#{mural[:dono]} - #{mural[:recados]}" -%></h4>
    </div>
  </a>
  <% end %>
</div>

app/views/mural/mostrar.html.erb
<div class="title">
  <h1>Mural de recados de <%= @mural.dono -%></h1>
</div>
<div>
  <% @recados.each do |recado| %>
  <div>
    <p><%= recado.mensagem.html_safe -%></p>
  </div>
  <% end %>
  <div>
    <h4>Deixe aqui seu recado para <%= @mural.dono -%>:</h4>
    <%= form_tag(enviar_path(@mural.id), method: "post") do %>
    <%= text_area_tag(:m, nil, rows: 5, cols: 80) %>
    <%= submit_tag("Enviar!") %>
    <% end %>
  </div>
</div>
<div class="footer">
  <h4><a href="<%= root_path -%>">Voltar</a></h4>
</div>